### ISSUE TITLE
Have the radar variables easier to change

### ISSUE THREAD

**Issue by kerberosmansour** [MichelleEmbleton/appSecRadar#16]
As a user of  the radar, I want its variables easier to change (if they are not already) like the number of layers or segments and to be able to rename them as needed. (I can help with the documentation).

This would open the radar to multiple use-cases.

**Comment by MichelleEmbleton** [comment]
That's a good idea.
Will add a list representation first, then make it take csv's

**Comment by kerberosmansour** [comment]
Just like we have `CAT:"app", `
Can we have `Status:"PLAN_FOR_REMOVAL"`
That way we don't have rows of : `PLAN_FOR_REMOVAL:"y", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"",`
Think that should look much neater.

**Comment by MichelleEmbleton** [comment]
I agree that would look neater.
The reason I did it this way - with separate headings for each status - was so that just a 'y' or 'x' (or any entry) could be made for the status chosen (like an option menu) - so mitigate against invalid / mis-spelt entries - but, yes, you're right - that would be better, then they can also be renamed..
Invalid entries can appear in the Anomaly chart anyway..

**Comment by MichelleEmbleton** [comment]
Just uploaded the latest changes, Sherif.
Let me know what you think...
